### ISSUE TITLE
nsfw

### ISSUE THREAD

**Issue by odragit** [ilmanhdyt/ShiraoriBOT-Md#10]
.on nsfw 
error bg
TypeError: Cannot set property 'nsfw' of undefined
    at Object.handler (enable.js:118:20)
    at Object.handler (handler.js:372:38)

**Comment by Uhdahlah** [comment]
> .on nsfw error bg TypeError: Cannot set property 'nsfw' of undefined at Object.handler (enable.js:118:20) at Object.handler (handler.js:372:38)

.on anticall juga ga work di aku
