### ISSUE TITLE
[REQUEST] Req Fitur bang

### ISSUE THREAD

**Issue by Hbz-Dev** [ilmanhdyt/ShiraoriBOT-Md#16]
-broadcast
-more scrape fitur
-Kurangin fitur yg make api
-Tambahin Buttonnya (masih dikit)
-List Message menu 
-Fix Error in login
-Add more nsfw fitur
-Add more game fitur
-Intinya perbanyak pluginsnya 🗿🥀

gamaksa kok bang
cuma saran :)
@ilmanhdyt sini bang wowkwk

**Comment by akmallxx** [comment]
bc keknya blm bisa deh buat baileys md, tpi klo fitur nsfw bisa pake https://waifu.pics/docs

**Comment by BochilGaming** [comment]
> bc keknya blm bisa deh buat baileys md, tpi klo fitur nsfw bisa pake https://waifu.pics/docs

Kalau bc udh support,  cara dapetin nomornya pakek conn.chats
