### ISSUE TITLE
Menu emror

### ISSUE THREAD

**Issue by jauhariel** [ilmanhdyt/ShiraoriBOT-Md#19]
![Screenshot_2022-01-11-12-49-52-59](https://user-images.githubusercontent.com/92896736/148889139-46339a9c-537c-459d-b88d-547dcab78db5.jpg)

**Comment by ilmanhdyt** [comment]
Device lu

**Comment by jauhariel** [comment]
> Device lu

Kenapa tuh devicenya?

**Comment by ilmanhdyt** [comment]
Ya baca tr sendiri
