### ISSUE TITLE
Not connecting 

### ISSUE THREAD

**Issue by Cosm1cBug** [ilmanhdyt/ShiraoriBOT-Md#22]
{
    "connection": "close",
    "lastDisconnect": {
        "error": {
            "data": null,
            "isBoom": true,
            "isServer": false,
            "output": {
                "statusCode": 411,
                "payload": {
                    "statusCode": 411,
                    "error": "Length Required",
                    "message": "Multi-device beta not joined"
                },
                "headers": {}
            }
        },
        "date": "2022-01-19T14:40:39.581Z"
    }
}
{
    "connection": "connecting",
    "receivedPendingNotifications": false
}

**Comment by BochilGaming** [comment]
> { "connection": "close", "lastDisconnect": { "error": { "data": null, "isBoom": true, "isServer": false, "output": { "statusCode": 411, "payload": { "statusCode": 411, "error": "Length Required", "message": "Multi-device beta not joined" }, "headers": {} } }, "date": "2022-01-19T14:40:39.581Z" } } { "connection": "connecting", "receivedPendingNotifications": false }

join multi-device
