### ISSUE TITLE
a

### ISSUE THREAD

**Issue by natxdixie** [ilmanhdyt/ShiraoriBOT-Md#23]
ngga bisa worker: node . --db 'https://json-server-1.' kah?

**Comment by aniq12** [comment]
dh di coba?

**Comment by natxdixie** [comment]
> dh di coba?

iyo udah eror malah

**Comment by Hbz-Dev** [comment]
> ngga bisa worker: node . --db 'https://json-server-1.' kah?

Bisa njir
pake mongoDB

**Comment by natxdixie** [comment]
> > ngga bisa worker: node . --db 'https://json-server-1.' kah?
> 
> Bisa njir pake mongoDB

make db replit gaiso kah kaya node . --db 'https://json-server.nurutomo.repl.co/' :3

**Comment by natxdixie** [comment]
![Screenshot_2022-01-23-18-41-26-01](https://user-images.githubusercontent.com/83612604/150676690-864717e3-dae5-4972-81b4-6eb69a6e6a7e.jpg)

![Screenshot_2022-01-23-18-41-10-97](https://user-images.githubusercontent.com/83612604/150676696-4e51824b-438d-4c8b-9b5f-b4cb98f13204.jpg)
nih bang nyiba make mongodb kok nda ada respon ya botnya

**Comment by Jauhariq** [comment]
Join https://discord.gg/2sDBYudEad

Noh kali aja butuh hosting bot unlimited gratis tanpa nyambungin db.

**Comment by Jauhariq** [comment]
![Uploading IMG_20220202_115719.jpg…]()

**Comment by Jauhariq** [comment]
![IMG_20220202_115719](https://user-images.githubusercontent.com/92896736/152095558-951d76dd-2ad5-49dd-b01c-cca7e621e8c1.jpg)

**Comment by jauhariel** [comment]
Kali aja butuh alternatif hosting buat bot gratis
https://bit.ly/3ryzu4Q

**Comment by natxdixie** [comment]
> Kali aja butuh alternatif hosting buat bot gratis https://bit.ly/3ryzu4Q

makasih ingfonya banh

**Comment by natxdixie** [comment]
> Kali aja butuh alternatif hosting buat bot gratis https://bit.ly/3ryzu4Q

gada yg nodejs kah?

**Comment by jauhariel** [comment]
> > Kali aja butuh alternatif hosting buat bot gratis https://bit.ly/3ryzu4Q
> 
> gada yg nodejs kah?

Gua pake discord js disitu kan ada, terus pilih versi nodejsnya tinggal sesuain dll terus tinggal upload file botnya dipanel terus tinggal start otomatis nginstall dan jalan botnya. 

Untuk server gua saranin lu pake yg UK

**Comment by natxdixie** [comment]
> > > Kali aja butuh alternatif hosting buat bot gratis https://bit.ly/3ryzu4Q
> > 
> > 
> > gada yg nodejs kah?
> 
> Gua pake discord js disitu kan ada, terus pilih versi nodejsnya tinggal sesuain dll terus tinggal upload file botnya dipanel terus tinggal start otomatis nginstall dan jalan botnya.
> 
> Untuk server gua saranin lu pake yg UK

wokeh makasih bang ingfonya :^
