### ISSUE TITLE
bang saya mau nambah fitur boleh apa ngga bang

### ISSUE THREAD

**Issue by NadhiraAlifah** [ilmanhdyt/ShiraoriBOT-Md#24]

**Comment by ilmanhdyt** [comment]
Tambah aja

**Comment by NadhiraAlifah** [comment]
tapi bang

**Comment by NadhiraAlifah** [comment]
saya ga ngerti cara nambahnya soal nya beda base sama saya

**Comment by BochilGaming** [comment]
> saya ga ngerti cara nambahnya soal nya beda base sama saya

F

**Comment by NadhiraAlifah** [comment]
> > saya ga ngerti cara nambahnya soal nya beda base sama saya
> 
> F

nih bang saya mau update ini
[Source-code](https://github.com/NadhiraAlifah/whatsapp-bot-MD)

**Comment by kryzzp** [comment]
F
