### ISSUE TITLE
ditunggu finalnya XD

### ISSUE THREAD

**Issue by akmallxx** [ilmanhdyt/ShiraoriBOT-Md#3]
btw req welcome **knights canvas** :3

```js
const knights = require('knights-canvas')

let wel = await new knights.Welcome()
                .setUsername(this.getName(user))
                .setGuildName(this.getName(jid))
                .setGuildIcon(ppgcUrl)
                .setMemberCount(groupMetadata.participants.length)
                .setAvatar(ppUrl)
                .setBackground(bgUrl)
                .toAttachment()

let lea = await new knights.Goodbye()
                .setUsername(this.getName(user))
                .setGuildName(this.getName(jid))
                .setGuildIcon(ppgcUrl)
                .setMemberCount(groupMetadata.participants.length)
                .setAvatar(ppUrl)
                .setBackground(bgUrl)
                .toAttachment()

this.sendFile(jid, action === 'add' ? await wel.toBuffer() : await lea.toBuffer(), 'pp.jpg', text, null, false, {
                contextInfo: {
                  mentionedJid: [user]
                }
              })
```

**Comment by Hbz-Dev** [comment]
> btw req welcome **knights canvas** :3
> 
> ```js
> const knights = require('knights-canvas')
> 
> let wel = await new knights.Welcome()
>                 .setUsername(this.getName(user))
>                 .setGuildName(this.getName(jid))
>                 .setGuildIcon(ppgcUrl)
>                 .setMemberCount(groupMetadata.participants.length)
>                 .setAvatar(ppUrl)
>                 .setBackground(bgUrl)
>                 .toAttachment()
> 
> let lea = await new knights.Goodbye()
>                 .setUsername(this.getName(user))
>                 .setGuildName(this.getName(jid))
>                 .setGuildIcon(ppgcUrl)
>                 .setMemberCount(groupMetadata.participants.length)
>                 .setAvatar(ppUrl)
>                 .setBackground(bgUrl)
>                 .toAttachment()
> 
> this.sendFile(jid, action === 'add' ? wel.toBuffer() : lea.toBuffer(), 'pp.jpg', text, null, false, {
>                 contextInfo: {
>                   mentionedJid: [user]
>                 }
>               })
> ```

keren izin comot yak

**Comment by ilmanhdyt** [comment]
> btw req welcome **knights canvas** :3
> 
> ```js
> const knights = require('knights-canvas')
> 
> let wel = await new knights.Welcome()
>                 .setUsername(this.getName(user))
>                 .setGuildName(this.getName(jid))
>                 .setGuildIcon(ppgcUrl)
>                 .setMemberCount(groupMetadata.participants.length)
>                 .setAvatar(ppUrl)
>                 .setBackground(bgUrl)
>                 .toAttachment()
> 
> let lea = await new knights.Goodbye()
>                 .setUsername(this.getName(user))
>                 .setGuildName(this.getName(jid))
>                 .setGuildIcon(ppgcUrl)
>                 .setMemberCount(groupMetadata.participants.length)
>                 .setAvatar(ppUrl)
>                 .setBackground(bgUrl)
>                 .toAttachment()
> 
> this.sendFile(jid, action === 'add' ? wel.toBuffer() : lea.toBuffer(), 'pp.jpg', text, null, false, {
>                 contextInfo: {
>                   mentionedJid: [user]
>                 }
>               })
> ```

Buat pr aja:v

**Comment by akmallxx** [comment]
> > btw req welcome **knights canvas** :3
> > ```js
> > const knights = require('knights-canvas')
> > 
> > let wel = await new knights.Welcome()
> >                 .setUsername(this.getName(user))
> >                 .setGuildName(this.getName(jid))
> >                 .setGuildIcon(ppgcUrl)
> >                 .setMemberCount(groupMetadata.participants.length)
> >                 .setAvatar(ppUrl)
> >                 .setBackground(bgUrl)
> >                 .toAttachment()
> > 
> > let lea = await new knights.Goodbye()
> >                 .setUsername(this.getName(user))
> >                 .setGuildName(this.getName(jid))
> >                 .setGuildIcon(ppgcUrl)
> >                 .setMemberCount(groupMetadata.participants.length)
> >                 .setAvatar(ppUrl)
> >                 .setBackground(bgUrl)
> >                 .toAttachment()
> > 
> > this.sendFile(jid, action === 'add' ? wel.toBuffer() : lea.toBuffer(), 'pp.jpg', text, null, false, {
> >                 contextInfo: {
> >                   mentionedJid: [user]
> >                 }
> >               })
> > ```
> 
> Buat pr aja:v

ehehe :D
