### ISSUE TITLE
Button Image

### ISSUE THREAD

**Issue by anggita13** [ilmanhdyt/ShiraoriBOT-Md#32]
Adakah contoh buat button Image nya kak?

**Comment by akmallxx** [comment]
conn.sendButtonImg(m.chat, blabla)

**Comment by akmallxx** [comment]
cek aj di [`simple.js`](https://github.com/ilmanhdyt/ShiraoriBOT-Md/blob/Multi-Device/lib/simple.js)

**Comment by anggita13** [comment]
> cek aj di [`simple.js`](https://github.com/ilmanhdyt/ShiraoriBOT-Md/blob/Multi-Device/lib/simple.js)

![Screenshot_20220216-060147_WhatsApp](https://user-images.githubusercontent.com/86518199/154164432-9c264236-00cd-4c90-a891-40cc5fa95349.png)
Makasih kak, sudah bisa
