### ISSUE TITLE
Ga bisa send Media

### ISSUE THREAD

**Issue by RTeam1** [ilmanhdyt/ShiraoriBOT-Md#33]
Ga bisa send media Selain gambar, saya coba yang play alhasil cuma thumbnail nya yg dikasih, musik atau video nya kagak dikasih😪

Oh iya stiker juga kagak respon tuh, ngetik #sticker ga di respon, seharusnya dia balas kek gini "kirim gambar/video dengan caption #stiker" atau semacamnya gitu, intinya command stiker ga respon...

Semangat buat para developer Bot
Semoga dibaca:)

**Comment by barxnl** [comment]
> Ga bisa send media Selain gambar, saya coba yang play alhasil cuma thumbnail nya yg dikasih, musik atau video nya kagak dikasih😪
> 
> Oh iya stiker juga kagak respon tuh, ngetik #sticker ga di respon, seharusnya dia balas kek gini "kirim gambar/video dengan caption #stiker" atau semacamnya gitu, intinya command stiker ga respon...
> 
> Semangat buat para developer Bot Semoga dibaca:)

Replace https jadi http di y2mate biar work fitur downloader yt nya

**Comment by jauhariel** [comment]
> > Ga bisa send media Selain gambar, saya coba yang play alhasil cuma thumbnail nya yg dikasih, musik atau video nya kagak dikasih😪
> > Oh iya stiker juga kagak respon tuh, ngetik #sticker ga di respon, seharusnya dia balas kek gini "kirim gambar/video dengan caption #stiker" atau semacamnya gitu, intinya command stiker ga respon...
> > Semangat buat para developer Bot Semoga dibaca:)
> 
> Replace https jadi http di y2mate biar work fitur downloader yt nya

y2mate.js ? Di folder lib? Line ke?

**Comment by ilmanhdyt** [comment]
> > > Ga bisa send media Selain gambar, saya coba yang play alhasil cuma thumbnail nya yg dikasih, musik atau video nya kagak dikasihsleepy
> > > Oh iya stiker juga kagak respon tuh, ngetik #sticker ga di respon, seharusnya dia balas kek gini "kirim gambar/video dengan caption #stiker" atau semacamnya gitu, intinya command stiker ga respon...
> > > Semangat buat para developer Bot Semoga dibaca:)
> > 
> > 
> > Replace https jadi http di y2mate biar work fitur downloader yt nya
> 
> y2mate.js ? Di folder lib? Line ke?

[https://github.com/ilmanhdyt/ShiraoriBOT-Md/blob/Multi-Device/lib/y2mate.js](url) 30?

**Comment by jauhariel** [comment]
> > > > Ga bisa send media Selain gambar, saya coba yang play alhasil cuma thumbnail nya yg dikasih, musik atau video nya kagak dikasihsleepy
> > > > Oh iya stiker juga kagak respon tuh, ngetik #sticker ga di respon, seharusnya dia balas kek gini "kirim gambar/video dengan caption #stiker" atau semacamnya gitu, intinya command stiker ga respon...
> > > > Semangat buat para developer Bot Semoga dibaca:)
> > > 
> > > 
> > > Replace https jadi http di y2mate biar work fitur downloader yt nya
> > 
> > 
> > y2mate.js ? Di folder lib? Line ke?
> 
> [https://github.com/ilmanhdyt/ShiraoriBOT-Md/blob/Multi-Device/lib/y2mate.js](url) 30?

Di gua malah servernya jadi eror semua

**Comment by z3r0-d4y-3xplo1t** [comment]
Folder tmp lu ada ga v
