### ISSUE TITLE
Tambahin antilink bang

### ISSUE THREAD

**Issue by natxdixie** [ilmanhdyt/ShiraoriBOT-Md#4]
Tambahin antilink bang

**Comment by ilmanhdyt** [comment]
> Tambahin antilink bang

![Screenshot_2021-12-22-08-52-16-74](https://user-images.githubusercontent.com/87686497/147016744-12e5caa2-8667-4980-893e-6c44fe4e73e4.jpg)
Done

**Comment by ilmanhdyt** [comment]
Dah
![Screenshot_2021-12-22-08-52-16-74](https://user-images.githubusercontent.com/87686497/147016810-d75d03f4-1942-4588-bb82-2b9fe1da4aef.jpg)

**Comment by natxdixie** [comment]
> Dah ![Screenshot_2021-12-22-08-52-16-74](https://user-images.githubusercontent.com/87686497/147016810-d75d03f4-1942-4588-bb82-2b9fe1da4aef.jpg)

Anjay mantao bang semangatt
